services:
  biblingo:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: biblingo
    env_file:
      - ./api/.env
    ports:
      - "8082:8082"  # Web (Landing Page)
      - "8083:8083"  # App (Vue SPA)
      - "8084:8084"  # API (PHP Backend)
    volumes:
      - ./web:/var/www/web:ro
      - ./app/dist:/var/www/app:ro
      - ./api:/var/www/api
    restart: always
