FROM nginx:alpine

# Copiar la configuración personalizada de Nginx
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

# Copiar los sitios web
COPY web /var/www/web
COPY app/dist /var/www/app/dist

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
